# Generated by Django 6.0 on 2025-12-23 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Unique ID from platform', max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField(help_text='When posted on original platform')),
                ('status', models.CharField(choices=[('new', 'New'), ('alerted', 'Alerted'), ('sent', 'Sent'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DraftMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('platform', models.CharField(choices=[('reddit_comment', 'Reddit Comment'), ('reddit_dm', 'Reddit DM'), ('email', 'Email')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='core.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='AlertStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_message_id', models.CharField(max_length=255)),
                ('acknowledged', models.BooleanField(default=False)),
                ('job_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='core.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_job_signal', models.BooleanField(default=False)),
                ('confidence', models.FloatField(help_text='0.0 to 1.0')),
                ('classification', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('ignore', 'Ignore')], max_length=20)),
                ('reasoning', models.TextField(help_text='AI explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='core.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reddit', 'Reddit'), ('newsletter', 'Newsletter')], max_length=20)),
                ('identifier', models.CharField(help_text='Subreddit name or email sender', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('type', 'identifier')},
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='core.source'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['-timestamp'], name='core_jobpos_timesta_211a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status'], name='core_jobpos_status_d8405c_idx'),
        ),
    ]
