# Generated by Django 6.0 on 2025-12-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, help_text='Friendly display name', max_length=255),
        ),
    ]
