# Generated by Django 6.0 on 2025-12-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftmessage',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Cover letter for email outreach'),
        ),
        migrations.AlterField(
            model_name='source',
            name='identifier',
            field=models.CharField(help_text="Subreddit name or keyword for newsletter matching (e.g., 'glassdoor', 'linkedin')", max_length=255),
        ),
    ]
