# Generated by Django 5.2.9 on 2025-12-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_draftmessage_cover_letter_alter_source_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='user_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('ignored', 'Ignored')], default='pending', help_text='User action status', max_length=20),
        ),
    ]
