# Generated by Django 5.2.9 on 2025-12-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobpost_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='raw_html',
            field=models.TextField(blank=True, help_text='Original HTML content for emails'),
        ),
    ]
