# Generated by Django 5.2.8 on 2025-12-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobpost_raw_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='application_link',
            field=models.URLField(blank=True, help_text='Actual job application link (LinkedIn, Glassdoor, etc.)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='url',
            field=models.URLField(help_text='Reddit post URL or email mailto link', max_length=500),
        ),
    ]
