# Generated by Django 5.2.8 on 2025-12-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobpost_application_link_alter_jobpost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(blank=True, help_text='Full-time, Contract, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, help_text='Location or Remote', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills_tags',
            field=models.TextField(blank=True, help_text='Comma-separated skills/tags'),
        ),
        migrations.AddField(
            model_name='source',
            name='base_url',
            field=models.URLField(blank=True, help_text='Base URL for scraping', max_length=500),
        ),
        migrations.AddField(
            model_name='source',
            name='rate_limit_seconds',
            field=models.IntegerField(default=5, help_text='Seconds between requests'),
        ),
        migrations.AddField(
            model_name='source',
            name='scraper_type',
            field=models.CharField(blank=True, help_text='beautifulsoup, selenium, api, rss', max_length=20),
        ),
        migrations.AlterField(
            model_name='draftmessage',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Full cover letter for job applications'),
        ),
        migrations.AlterField(
            model_name='draftmessage',
            name='platform',
            field=models.CharField(choices=[('github_comment', 'GitHub Comment'), ('direct_message', 'Direct Message'), ('cover_letter', 'Cover Letter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='application_link',
            field=models.URLField(blank=True, help_text='Direct application link', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='author',
            field=models.CharField(blank=True, help_text='Poster username/email', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='body',
            field=models.TextField(help_text='Job description'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='raw_html',
            field=models.TextField(blank=True, help_text='Original HTML content'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='url',
            field=models.URLField(help_text='Source URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='source',
            name='identifier',
            field=models.CharField(help_text='Board name, GitHub repo, or RSS feed URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('job_board', 'Job Board'), ('github_issue', 'GitHub Issue'), ('rss_feed', 'RSS Feed')], max_length=20),
        ),
    ]
